name: Tests

on: [ push, pull_request ]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-versions: [ '8.0', '8.1' ]
        phpunit-version: [ '9.5' ]
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring
          coverage: none
          tools: phpunit:${{ matrix.phpunit-version }}, composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Check PHP Extensions
        run: php -m

      - name: Check Composer Version
        run: composer -V

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate composer.json & composer.lock
        run: composer validate --strict

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-suggest

      - name: Run Tests
        run: composer test
